### PR TITLE
File and Folder Size scripts

### PR DESCRIPTION
**Pull request by shadyrudy**
First commit. Three new files which display: 

- Directory Size 
- Disk Space for drives / mount points
- Largest files in a directory in descending order

### CODE REVIEW

**Comment by shadyrudy** [comment]
This is the first commit. No issues since everything is new at this point. 
🐻 🟢 🟡

**Review by shadyrudy — COMMENTED** [review]
Initial version
Changes approved

**Review by RudyRodarte — APPROVED** [review]
Just the first commit.
Looks good.

**Comment by RudyRodarte** [comment]
First version 🌮 🍔

**Pull request merged**
